apiVersion: batch/v1
kind: CronJob
metadata:
  name: daily-job
spec:
  schedule: "0 0 * * *"
  jobTemplate:
    spec:
      template:
        spec:
          serviceAccountName: s3-access
          containers:
            - name: diego-container
              image: dcristobal/node-get-open-ports:0.0.6
              imagePullPolicy: Always
              env:
                - name: BUCKET_NAME
                  value: "s3-report-bucket-diego"
          restartPolicy: OnFailure
